### ISSUE TITLE
Kubernetes additional work required for deploying topology

### ISSUE THREAD

**Issue by windhamwong** [apache/incubator-heron#3542]
Kubernetes version: 1.18.2+k3s1
I am trying out to deploy `heron-api-examples.jar` as suggested in the doc. After some troubleshooting (not just some but a lot) and found that the created pods (`acking-0`, `acking-1`, `acking-2`) require to connect together. The `acking-0` is responsible for launching servers for stream manager (6001/TCP), tmaster controller (6002/TCP) and tmaster state (6003/TCP). As k8s requires `Service` to expose ports to allow external or other containers to connect, we need additional code in Heron k8s source to generate these services as well. The following k8s yaml code has been tested and working for me.

I will keep on testing out as the topology is still not working as the demo expectation. I will come back to add more after.

```
apiVersion: v1
kind: Service
metadata:
  name: acking-0
spec:
  selector:
    statefulset.kubernetes.io/pod-name: acking-0
  ports:
    - name: stream-manager
      protocol: TCP
      port: 6001
      targetPort: 6001
    - name: tmaster-controller
      protocol: TCP
      port: 6002
      targetPort: 6002
    - name: tmaster-state
      protocol: TCP
      port: 6003
      targetPort: 6003
    - name: heron-shell
      protocol: TCP
      port: 6004
      targetPort: 6004
```
